spring:
  config:
    import: dev-secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${secret.datasource.url}:${secret.datasource.port}/${secret.datasource.database}?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&autoReconnect=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: ${secret.datasource.username}
    password: ${secret.datasource.password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

cors:
  origin: ${secret.cors.origin}

oauth:
  client_id: ${secret.oauth.client_id}
  client_secret: ${secret.oauth.client_secret}
  redirect_uri: ${secret.oauth.redirect_uri}
  grant_type: ${secret.oauth.grant_type}

jwt:
  secret_key: ${secret.secret_key}
  access_token_expiration_millis: ${secret.access_token_expiration_millis}
  refresh_token_expiration_millis: ${secret.refresh_token_expiration_millis}
