name: debate-timer-server

include:
  - docker-compose.traefik.yaml
  - docker-compose.spring.yaml
  - docker-compose.datadog.yaml

networks:
  debate-timer-net:
    name: debate-timer-net
    driver: bridge
