x-app-template: &app-template
  image: debatetimer/debate_timer:${ENV:-dev}
  environment:
    - SERVER_FORWARD_HEADERS_STRATEGY=framework
    - SPRING_PROFILES_ACTIVE=${PROFILE:-dev,monitor}
    - TZ=Asia/Seoul

    - DD_AGENT_HOST=datadog-agent
    - DD_SERVICE=debate-timer
    - DD_ENV=${ENV:-dev}
    - DD_VERSION=1.0.0
    - DD_LOGS_INJECTION=true
    - DD_PROFILING_ENABLED=true
    - DD_PROFILING_ALLOCATION_ENABLED=true
    - DD_PROFILING_HEAP_ENABLED=true

    - MANAGEMENT_STATSD_METRICS_EXPORT_ENABLED=true
    - MANAGEMENT_STATSD_METRICS_EXPORT_FLAVOR=datadog
    - MANAGEMENT_STATSD_METRICS_EXPORT_HOST=datadog-agent
    - MANAGEMENT_STATSD_METRICS_EXPORT_PORT=8125
    - MANAGEMENT_STATSD_METRICS_EXPORT_PROTOCOL=UDP

  networks:
    - debate-timer-net

  depends_on:
    traefik:
      condition: service_healthy
    datadog-agent:
      condition: service_healthy

  healthcheck:
    test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/monitoring/health" ]
    interval: 60s
    retries: 5
    start_period: 300s

services:
  app-blue:
    <<: *app-template
    container_name: app-blue
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-blue.rule=Host(`api.${ENV:-dev}.debate-timer.com`)"
      - "traefik.http.routers.app-blue.entrypoints=websecure"
      - "traefik.http.routers.app-blue.tls=true"
      - "traefik.http.routers.app-blue.tls.certresolver=myresolver"
      - "traefik.http.services.app-blue.loadbalancer.server.port=8080"
      - "traefik.http.routers.app-blue.service=app-blue"

      - "traefik.http.routers.app-blue-monitor.rule=PathPrefix(`/`)"
      - "traefik.http.routers.app-blue-monitor.entrypoints=monitoring"
      - "traefik.http.routers.app-blue-monitor.service=app-blue-monitor-svc"
      - "traefik.http.services.app-blue-monitor-svc.loadbalancer.server.port=8083"

      - "com.datadoghq.ad.logs=[{\"source\": \"java\", \"service\": \"debate-timer\"}]"

  app-green:
    <<: *app-template
    container_name: app-green
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-green.rule=Host(`api.${ENV:-dev}.debate-timer.com`)"
      - "traefik.http.routers.app-green.entrypoints=websecure"
      - "traefik.http.routers.app-green.tls=true"
      - "traefik.http.routers.app-green.tls.certresolver=myresolver"
      - "traefik.http.services.app-green.loadbalancer.server.port=8080"
      - "traefik.http.routers.app-green.service=app-green"

      - "traefik.http.routers.app-green-monitor.rule=PathPrefix(`/`)"
      - "traefik.http.routers.app-green-monitor.entrypoints=monitoring"
      - "traefik.http.routers.app-green-monitor.service=app-green-monitor-svc"
      - "traefik.http.services.app-green-monitor-svc.loadbalancer.server.port=8083"

      - "com.datadoghq.ad.logs=[{\"source\": \"java\", \"service\": \"debate-timer\"}]"
