services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8083:8083"
    environment:
      - DOCKER_API_VERSION=1.44
    command:
      - "--api.insecure=true"
      - "--ping=true"
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"

      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=debatetimekeeping@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

      - "--entrypoints.monitoring.address=:8083"
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8080/ping"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 120s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../letsencrypt:/letsencrypt
    networks:
      - debate-timer-net
