name: dev-cd

on:
  push:
    branches:
      - "chore/#57"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEV_DB_HOST: ${{ secrets.DEV_DB_HOST }}
      DEV_DB_DATABASE_NAME: ${{ secrets.DEV_DB_DATABASE_NAME }}
      DEV_DB_USERNAME: ${{ secrets.DEV_DB_USERNAME }}
      DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}

    steps:
      - name: Checkout Develop Branch
        uses: actions/checkout@v4
        with:
          ref: "chore/#57"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: bootJar with Gradle
        run: ./gradlew bootJar --info

      - name: Change artifact file name
        run: mv build/libs/*.jar build/libs/app.jar

      - name: Upload artifact file
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: ./build/libs/app.jar
          if-no-files-found: error

      - name: Upload deploy scripts
        uses: actions/upload-artifact@v4
        with:
          name: deploy-scripts
          path: ./backend/scripts/dev/
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: dev

    steps:
      - name: Download artifact file
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: ~/app

      - name: Download deploy scripts
        uses: actions/download-artifact@v4
        with:
          name: deploy-scripts
          path: ~/app/scripts

      - name: Replace application to latest
        run: sudo sh ~/app/scripts/replace-new-version.sh
